# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('type', models.CharField(choices=[('customer', 'Client'), ('supplier', 'Fournisseur'), ('both', 'Client et Fournisseur')], default='customer', max_length=20, verbose_name='Type')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Raison sociale')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='N° contribuable')),
                ('trade_register', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='Adresse (suite)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('credit_limit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Limite de crédit')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('discount_rate', apps.core.models.PercentageField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de remise (%)')),
                ('customer_accounting_code', models.CharField(blank=True, max_length=20, verbose_name='Compte comptable client')),
                ('supplier_accounting_code', models.CharField(blank=True, max_length=20, verbose_name='Compte comptable fournisseur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='tenancy.currency', verbose_name='Devise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'db_table': 'partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('type', models.CharField(choices=[('billing', 'Facturation'), ('shipping', 'Livraison'), ('both', 'Facturation et Livraison')], default='both', max_length=20, verbose_name='Type')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'adresse")),
                ('street', models.CharField(max_length=255, verbose_name='Adresse')),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='Adresse (suite)')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='partners.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'db_table': 'partner_address',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Nom de la banque')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='Code banque')),
                ('branch_code', models.CharField(blank=True, max_length=20, verbose_name='Code guichet')),
                ('account_number', models.CharField(max_length=50, verbose_name='Numéro de compte')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=20, verbose_name='SWIFT/BIC')),
                ('account_holder', models.CharField(blank=True, max_length=255, verbose_name='Titulaire du compte')),
                ('is_default', models.BooleanField(default=False, verbose_name='Compte par défaut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'db_table': 'partner_bank_account',
                'ordering': ['-is_default', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='partners.partnercategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de partenaire',
                'verbose_name_plural': 'Catégories de partenaires',
                'db_table': 'partner_category',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.partnercategory', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'partner_contact',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('company', 'code')},
        ),
    ]
