# Generated by Django 6.0.2 on 2026-02-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du fournisseur non enregistré', max_length=255, verbose_name='Nom fournisseur (saisie libre)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du fournisseur non enregistré', max_length=255, verbose_name='Nom fournisseur (saisie libre)'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='supplier_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du fournisseur non enregistré', max_length=255, verbose_name='Nom fournisseur (saisie libre)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du fournisseur non enregistré', max_length=255, verbose_name='Nom fournisseur (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='partners.partner', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partner', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_received', to='partners.partner', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='partners.partner', verbose_name='Fournisseur'),
        ),
    ]
