# Generated by Django 6.0.2 on 2026-02-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_tax_exempt_alter_product_tax_rate'),
        ('purchasing', '0002_goodsreceipt_supplier_name_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='requestforquotationline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='requestforquotationline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='catalog.product', verbose_name='Produit'),
        ),
    ]
