# Generated by Django 6.0.2 on 2026-02-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='partner_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du client non enregistré', max_length=255, verbose_name='Nom client (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='partner_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du client non enregistré', max_length=255, verbose_name='Nom client (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='partner_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du client non enregistré', max_length=255, verbose_name='Nom client (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='partner_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du client non enregistré', max_length=255, verbose_name='Nom client (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='partners.partner', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.partner', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='salesquote',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotes', to='partners.partner', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='partners.partner', verbose_name='Client'),
        ),
    ]
