# Generated by Django 6.0.2 on 2026-02-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_tax_exempt_alter_product_tax_rate'),
        ('sales', '0002_salesinvoice_partner_name_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='product_name_manual',
            field=models.CharField(blank=True, default='', help_text='Nom du produit non enregistré', max_length=255, verbose_name='Nom produit (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='salesquoteline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quote_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_lines', to='catalog.product', verbose_name='Produit'),
        ),
    ]
