# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPriceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur de la remise')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide à partir de')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('priority', models.PositiveIntegerField(default=10, help_text='Plus le nombre est bas, plus la priorité est haute', verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer à toutes les catégories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_price_rules', to='catalog.productcategory', verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='partners.partner', verbose_name='Client')),
                ('product', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer à tous les produits', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_price_rules', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Règle de prix client',
                'verbose_name_plural': 'Règles de prix clients',
                'db_table': 'customer_price_rule',
                'ordering': ['partner', 'priority', 'product'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Liste par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide à partir de')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='tenancy.currency', verbose_name='Devise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Liste de prix',
                'verbose_name_plural': 'Listes de prix',
                'db_table': 'price_list',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(help_text='Code à saisir par le client', max_length=50, verbose_name='Code promo')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe'), ('buy_x_get_y', 'Achetez X, obtenez Y')], default='percentage', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pourcentage ou montant selon le type', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur')),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text="Pour promotions 'Achetez X, obtenez Y'", null=True, verbose_name='Quantité à acheter (X)')),
                ('get_quantity', models.PositiveIntegerField(blank=True, help_text="Pour promotions 'Achetez X, obtenez Y'", null=True, verbose_name='Quantité offerte (Y)')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_to', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('min_purchase_amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Montant minimum de la commande pour appliquer la promotion', max_digits=15, verbose_name="Montant d'achat minimum")),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name="Nombre d'utilisations maximum")),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotion',
                'ordering': ['-valid_from', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('min_quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité minimum')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Laisser vide pour illimité', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité maximum')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur de la remise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Remise sur volume',
                'verbose_name_plural': 'Remises sur volume',
                'db_table': 'volume_discount',
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Prix applicable à partir de cette quantité', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité minimum')),
                ('unit_price', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix unitaire HT')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist', verbose_name='Liste de prix')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de liste de prix',
                'verbose_name_plural': 'Articles de listes de prix',
                'db_table': 'price_list_item',
                'ordering': ['price_list', 'product', 'min_quantity'],
                'unique_together': {('price_list', 'product', 'min_quantity')},
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.product', verbose_name='Produit')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Produit en promotion',
                'verbose_name_plural': 'Produits en promotion',
                'db_table': 'promotion_product',
                'ordering': ['promotion', 'product'],
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
