# Generated by Django 5.0.4 on 2026-02-09 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Nom légal')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='N° contribuable')),
                ('trade_register', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='Adresse (suite)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, verbose_name="Mois de début d'exercice")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Décimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'db_table': 'currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_receivable_account', models.CharField(default='411000', max_length=20, verbose_name='Compte client par défaut')),
                ('default_payable_account', models.CharField(default='401000', max_length=20, verbose_name='Compte fournisseur par défaut')),
                ('default_sales_account', models.CharField(default='701000', max_length=20, verbose_name='Compte de vente par défaut')),
                ('default_purchase_account', models.CharField(default='601000', max_length=20, verbose_name="Compte d'achat par défaut")),
                ('default_vat_collected_account', models.CharField(default='443100', max_length=20, verbose_name='Compte TVA collectée')),
                ('default_vat_deductible_account', models.CharField(default='445600', max_length=20, verbose_name='Compte TVA déductible')),
                ('default_payment_terms_days', models.PositiveSmallIntegerField(default=30, verbose_name='Délai de paiement par défaut (jours)')),
                ('quote_validity_days', models.PositiveSmallIntegerField(default=30, verbose_name='Validité des devis (jours)')),
                ('default_valuation_method', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('average', 'Coût moyen pondéré')], default='average', max_length=20, verbose_name='Méthode de valorisation')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='Autoriser stock négatif')),
                ('invoice_notes', models.TextField(blank=True, verbose_name='Notes sur factures')),
                ('invoice_footer', models.TextField(blank=True, verbose_name='Pied de page factures')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenancy.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprises',
                'db_table': 'company_settings',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='tenancy.currency', verbose_name='Devise principale'),
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé'), ('locked', 'Verrouillé')], default='open', max_length=20, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='tenancy.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Exercice fiscal',
                'verbose_name_plural': 'Exercices fiscaux',
                'db_table': 'fiscal_year',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_headquarters', models.BooleanField(default=False, verbose_name='Siège social')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenancy.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Succursale',
                'verbose_name_plural': 'Succursales',
                'db_table': 'branch',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Taux')),
                ('date', models.DateField(verbose_name='Date')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='tenancy.currency', verbose_name='Devise source')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='tenancy.currency', verbose_name='Devise cible')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'db_table': 'exchange_rate',
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Numéro')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé')], default='open', max_length=20, verbose_name='Statut')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='tenancy.fiscalyear', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Période comptable',
                'verbose_name_plural': 'Périodes comptables',
                'db_table': 'fiscal_period',
                'ordering': ['fiscal_year', 'number'],
                'unique_together': {('fiscal_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50, verbose_name='Type de document')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='Préfixe')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='Suffixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Remplissage')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
                ('reset_on_fiscal_year', models.BooleanField(default=True, verbose_name='Réinitialiser par exercice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='tenancy.company', verbose_name='Entreprise')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='tenancy.fiscalyear', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Séquence de numérotation',
                'verbose_name_plural': 'Séquences de numérotation',
                'db_table': 'document_sequence',
                'unique_together': {('company', 'document_type', 'fiscal_year')},
            },
        ),
    ]
