# Generated by Django 5.0.4 on 2026-02-14 07:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux de TVA par défaut (%)'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone WhatsApp pour alertes'),
        ),
    ]
