# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('opening_debit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Débit ouverture')),
                ('opening_credit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Crédit ouverture')),
                ('period_debit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Débit période')),
                ('period_credit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Crédit période')),
                ('closing_debit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Débit clôture')),
                ('closing_credit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Crédit clôture')),
            ],
            options={
                'verbose_name': 'Solde de compte',
                'verbose_name_plural': 'Soldes de comptes',
                'db_table': 'accounting_account_balance',
                'ordering': ['account__code', 'fiscal_period'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Libellé')),
                ('account_class', models.CharField(choices=[('1', 'Classe 1 - Comptes de ressources durables'), ('2', "Classe 2 - Comptes d'actif immobilisé"), ('3', 'Classe 3 - Comptes de stocks'), ('4', 'Classe 4 - Comptes de tiers'), ('5', 'Classe 5 - Comptes de trésorerie'), ('6', 'Classe 6 - Comptes de charges'), ('7', 'Classe 7 - Comptes de produits'), ('8', 'Classe 8 - Comptes des autres charges'), ('9', 'Classe 9 - Comptes analytiques')], max_length=1, verbose_name='Classe OHADA')),
                ('nature', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('income', 'Produits'), ('expense', 'Charges')], max_length=20, verbose_name='Nature')),
                ('is_debit_balance', models.BooleanField(default=True, verbose_name='Solde débiteur par défaut')),
            ],
            options={
                'verbose_name': 'Type de compte',
                'verbose_name_plural': 'Types de compte',
                'db_table': 'accounting_account_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Libellé')),
                ('journal_type', models.CharField(choices=[('sales', 'Journal des ventes'), ('purchases', 'Journal des achats'), ('bank', 'Journal de banque'), ('cash', 'Journal de caisse'), ('general', 'Journal des opérations diverses')], default='general', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sequence_prefix', models.CharField(blank=True, max_length=10, verbose_name='Préfixe de séquence')),
                ('next_sequence', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'accounting_journal',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('number', models.CharField(max_length=50, verbose_name='Numéro')),
                ('date', models.DateField(verbose_name='Date comptable')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.TextField(verbose_name='Libellé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('posted', 'Validée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_debit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total débit')),
                ('total_credit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total crédit')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='Est une extourne')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'accounting_journal_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('debit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Débit')),
                ('credit', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Crédit')),
                ('analytic_account', models.CharField(blank=True, max_length=50, verbose_name='Compte analytique')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('reconciled', models.BooleanField(default=False, verbose_name='Lettrée')),
                ('reconciliation_number', models.CharField(blank=True, max_length=20, verbose_name='N° lettrage')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'db_table': 'accounting_journal_entry_line',
                'ordering': ['entry', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code comptable')),
                ('name', models.CharField(max_length=200, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_reconcilable', models.BooleanField(default=False, verbose_name='Lettrable')),
                ('is_detail', models.BooleanField(default=True, verbose_name='Compte de détail')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='tenancy.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Plan comptable',
                'db_table': 'accounting_account',
                'ordering': ['code'],
            },
        ),
    ]
