# Generated by Django 5.0.4 on 2026-02-14 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_company_default_tax_rate_company_whatsapp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('monthly_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix mensuel')),
                ('yearly_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix annuel')),
                ('max_users', models.PositiveIntegerField(default=1, help_text='0 = illimité', verbose_name="Nombre max d'utilisateurs")),
                ('max_products', models.PositiveIntegerField(default=50, help_text='0 = illimité', verbose_name='Nombre max de produits')),
                ('has_scanner', models.BooleanField(default=False, verbose_name='Scanner')),
                ('has_csv_import', models.BooleanField(default=False, verbose_name='Import CSV')),
                ('has_full_cycles', models.BooleanField(default=False, verbose_name='Cycles complets')),
                ('has_dashboard', models.BooleanField(default=False, verbose_name='Tableau de bord')),
                ('has_multi_site', models.BooleanField(default=False, verbose_name='Multi-site')),
                ('has_offline_mode', models.BooleanField(default=False, verbose_name='Mode hors-ligne')),
                ('has_whatsapp_alerts', models.BooleanField(default=False, verbose_name='Alertes WhatsApp')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Accès API')),
                ('trial_days', models.PositiveIntegerField(default=30, verbose_name="Jours d'essai")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Plan plateforme',
                'verbose_name_plural': 'Plans plateforme',
                'db_table': 'platform_plan',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('past_due', 'Impayé'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=20, verbose_name='Statut')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Cycle de facturation')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name="Fin de l'essai")),
                ('current_period_start', models.DateField(verbose_name='Début période courante')),
                ('current_period_end', models.DateField(verbose_name='Fin période courante')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant facturé')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement auto')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenancy.company', verbose_name='Entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.platformplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonnement entreprise',
                'verbose_name_plural': 'Abonnements entreprises',
                'db_table': 'company_subscription',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID transaction')),
                ('payment_method', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('card', 'Carte bancaire'), ('manual', 'Manuel')], max_length=20, verbose_name='Moyen de paiement')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant')),
                ('currency_code', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('provider_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Réponse fournisseur')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.companysubscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
