# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('number', models.CharField(help_text='Généré automatiquement', max_length=50, verbose_name='Numéro')),
                ('payment_type', models.CharField(choices=[('customer', 'Client'), ('supplier', 'Fournisseur')], max_length=20, verbose_name='Type de paiement')),
                ('date', models.DateField(verbose_name='Date de paiement')),
                ('value_date', models.DateField(blank=True, help_text='Date effective du mouvement bancaire', null=True, verbose_name='Date de valeur')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmé'), ('reconciled', 'Rapproché'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Taux de change')),
                ('amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('amount_allocated', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant alloué')),
                ('amount_unallocated', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant non alloué')),
                ('reference', models.CharField(blank=True, help_text='N° chèque, n° transaction, etc.', max_length=100, verbose_name='Référence')),
                ('memo', models.TextField(blank=True, verbose_name='Mémo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments_payment',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant alloué')),
                ('allocation_date', models.DateField(verbose_name="Date d'allocation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Allocation de paiement',
                'verbose_name_plural': 'Allocations de paiement',
                'db_table': 'payments_allocation',
                'ordering': ['-allocation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('requires_reference', models.BooleanField(default=False, help_text='Exige une référence (n° chèque, n° transaction, etc.)', verbose_name='Référence requise')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'db_table': 'payments_method',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('days', models.PositiveIntegerField(default=0, help_text='Délai de paiement en jours', verbose_name='Nombre de jours')),
                ('is_immediate', models.BooleanField(default=False, help_text='Paiement comptant requis', verbose_name='Paiement immédiat')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise pour paiement anticipé', max_digits=5, verbose_name='Escompte (%)')),
                ('discount_days', models.PositiveIntegerField(default=0, help_text="Nombre de jours pour bénéficier de l'escompte", verbose_name='Jours pour escompte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
            ],
            options={
                'verbose_name': 'Condition de paiement',
                'verbose_name_plural': 'Conditions de paiement',
                'db_table': 'payments_term',
                'ordering': ['days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('number', models.CharField(help_text='Généré automatiquement', max_length=50, verbose_name='Numéro')),
                ('refund_type', models.CharField(choices=[('customer', 'Client'), ('supplier', 'Fournisseur')], max_length=20, verbose_name='Type de remboursement')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmé'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('reason', models.CharField(choices=[('overpayment', 'Trop-perçu'), ('credit_note', 'Avoir'), ('cancellation', 'Annulation'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Motif')),
                ('reason_details', models.TextField(blank=True, verbose_name='Détails du motif')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Taux de change')),
                ('amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'payments_refund',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
