# Generated by Django 5.0.4 on 2026-02-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('partners', '0001_initial'),
        ('payments', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.bankaccount', verbose_name='Compte bancaire'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.currency', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.journalentry', verbose_name='Écriture comptable'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.partner', verbose_name='Partenaire'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.salesinvoice', verbose_name='Facture client'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchasing.supplierinvoice', verbose_name='Facture fournisseur'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='treasury.bankaccount', verbose_name='Compte bancaire'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='accounting.journal', verbose_name='Journal comptable'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='treasury.bankaccount', verbose_name='Compte bancaire'),
        ),
        migrations.AddField(
            model_name='refund',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='refund',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.salesinvoice', verbose_name='Avoir associé'),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenancy.currency', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='refund',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='refund',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='accounting.journalentry', verbose_name='Écriture comptable'),
        ),
        migrations.AddField(
            model_name='refund',
            name='original_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.payment', verbose_name="Paiement d'origine"),
        ),
        migrations.AddField(
            model_name='refund',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_paid', to=settings.AUTH_USER_MODEL, verbose_name='Payé par'),
        ),
        migrations.AddField(
            model_name='refund',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='partners.partner', verbose_name='Partenaire'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentmethod', verbose_name='Méthode de paiement'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentterm',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='refund',
            unique_together={('company', 'number')},
        ),
    ]
