# Generated by Django 5.0.4 on 2026-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif'),
        ),
    ]
