# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('entity_type', models.CharField(choices=[('purchase_request', "Demande d'achat"), ('purchase_order', 'Commande fournisseur'), ('sales_quote', 'Devis'), ('sales_order', 'Commande client'), ('supplier_invoice', 'Facture fournisseur'), ('expense', 'Note de frais'), ('journal_entry', 'Écriture comptable')], max_length=50, verbose_name="Type d'entité")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_sequential', models.BooleanField(default=True, verbose_name='Approbation séquentielle')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name="Conditions d'activation")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Définition de workflow',
                'verbose_name_plural': 'Définitions de workflows',
                'db_table': 'workflow_definition',
                'ordering': ['entity_type', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('content_type', models.CharField(max_length=100, verbose_name="Type d'entité")),
                ('object_id', models.UUIDField(verbose_name="ID de l'entité")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Initié par')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Instance de workflow',
                'verbose_name_plural': 'Instances de workflows',
                'db_table': 'workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.workflowinstance', verbose_name='Instance')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'workflow_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('sequence', models.PositiveIntegerField(verbose_name='Ordre')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('action_type', models.CharField(choices=[('approve', 'Approbation'), ('review', 'Révision'), ('notify', 'Notification')], default='approve', max_length=20, verbose_name="Type d'action")),
                ('approver_role', models.CharField(blank=True, max_length=100, verbose_name='Rôle approbateur')),
                ('amount_threshold', apps.core.models.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Seuil montant')),
                ('auto_approve_below', models.BooleanField(default=False, verbose_name='Auto-approuver sous le seuil')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (heures)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('escalate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Escalader vers')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowdefinition', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Étape de workflow',
                'verbose_name_plural': 'Étapes de workflow',
                'db_table': 'workflow_step',
                'ordering': ['workflow', 'sequence'],
                'unique_together': {('workflow', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='workflow.workflowstep', verbose_name='Étape courante'),
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('action', models.CharField(choices=[('submit', 'Soumis'), ('approve', 'Approuvé'), ('reject', 'Rejeté'), ('request_info', "Demande d'info"), ('delegate', 'Délégué'), ('escalate', 'Escaladé')], max_length=20, verbose_name='Action')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='Délégué à')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow.workflowinstance', verbose_name='Instance')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='workflow.workflowstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Action de workflow',
                'verbose_name_plural': 'Actions de workflow',
                'db_table': 'workflow_action',
                'ordering': ['performed_at'],
            },
        ),
    ]
