# Generated by Django 6.0.2 on 2026-02-15 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_company_default_tax_rate_company_whatsapp_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_id', models.UUIDField(verbose_name='ID action client')),
                ('action_type', models.CharField(max_length=50, verbose_name="Type d'action")),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='ID entité')),
                ('status', models.CharField(choices=[('applied', 'Appliqué'), ('duplicate', 'Doublon'), ('failed', 'Échoué')], max_length=20, verbose_name='Statut')),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('payload', models.JSONField(default=dict, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_action_logs', to='tenancy.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'action sync",
                'verbose_name_plural': "Logs d'actions sync",
                'db_table': 'sync_action_log',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'action_id')},
            },
        ),
    ]
