# Generated by Django 5.0.4 on 2026-02-09 09:58

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_type', models.CharField(choices=[('select', 'Liste déroulante'), ('radio', 'Boutons radio'), ('color', 'Palette de couleurs')], default='select', max_length=20, verbose_name="Type d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Attribut de produit',
                'verbose_name_plural': 'Attributs de produits',
                'db_table': 'product_attribute',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('color_code', models.CharField(blank=True, help_text='Code hexadécimal (ex: #FF0000)', max_length=20, verbose_name='Code couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Valeur d'attribut",
                'verbose_name_plural': "Valeurs d'attributs",
                'db_table': 'product_attribute_value',
                'ordering': ['attribute', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(default=0, verbose_name='Gauche (arbre)')),
                ('rght', models.PositiveIntegerField(default=0, verbose_name='Droite (arbre)')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Niveau')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'db_table': 'product_category',
                'ordering': ['lft', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('image', models.ImageField(upload_to='catalog/products/gallery/', verbose_name='Image')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produits',
                'db_table': 'product_image',
                'ordering': ['product', '-is_primary', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('supplier_code', models.CharField(blank=True, max_length=50, verbose_name='Code fournisseur')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Désignation fournisseur')),
                ('purchase_price', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Prix d'achat")),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=15, verbose_name='Quantité minimum')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Délai de livraison (jours)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Fournisseur préféré')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Fournisseur de produit',
                'verbose_name_plural': 'Fournisseurs de produits',
                'db_table': 'product_supplier',
                'ordering': ['-is_preferred', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=50, verbose_name='Code variante')),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/variants/', verbose_name='Image')),
                ('purchase_price', apps.core.models.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Laissez vide pour utiliser le prix du produit', max_digits=15, null=True, verbose_name="Prix d'achat HT")),
                ('sale_price', apps.core.models.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Laissez vide pour utiliser le prix du produit', max_digits=15, null=True, verbose_name='Prix de vente HT')),
                ('price_extra', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Montant à ajouter au prix du produit', max_digits=15, verbose_name='Supplément de prix')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Variante de produit',
                'verbose_name_plural': 'Variantes de produits',
                'db_table': 'product_variant',
                'ordering': ['product', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('factor', models.DecimalField(decimal_places=6, help_text='Quantité source × facteur = quantité destination', max_digits=15, verbose_name='Facteur de conversion')),
            ],
            options={
                'verbose_name': "Conversion d'unité",
                'verbose_name_plural': "Conversions d'unités",
                'db_table': 'unit_conversion',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('unit', 'Unité'), ('weight', 'Poids'), ('volume', 'Volume'), ('length', 'Longueur'), ('time', 'Temps')], default='unit', max_length=20, verbose_name='Type')),
                ('ratio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text="Ratio par rapport à l'unité de base du même type", max_digits=15, verbose_name='Ratio')),
                ('is_reference', models.BooleanField(default=False, help_text='Unité de référence pour ce type', verbose_name='Unité de référence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'db_table': 'unit_of_measure',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('type', models.CharField(choices=[('product', 'Produit'), ('service', 'Service'), ('consumable', 'Consommable')], default='product', max_length=20, verbose_name='Type')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('barcode', models.CharField(blank=True, help_text='EAN/UPC', max_length=50, verbose_name='Code-barres')),
                ('internal_reference', models.CharField(blank=True, max_length=50, verbose_name='Référence interne')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='Image principale')),
                ('purchase_price', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Prix d'achat HT")),
                ('sale_price', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix de vente HT')),
                ('tax_rate', apps.core.models.PercentageField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de TVA (%)')),
                ('is_stockable', models.BooleanField(default=True, help_text='Décocher pour les services', verbose_name='Stockable')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Seuil d'alerte de stock bas", max_digits=15, verbose_name='Stock minimum')),
                ('max_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantité maximale à stocker', max_digits=15, verbose_name='Stock maximum')),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (Premier entré, premier sorti)'), ('lifo', 'LIFO (Dernier entré, premier sorti)'), ('average', 'Coût moyen pondéré')], default='average', max_length=20, verbose_name='Méthode de valorisation')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume (m³)')),
                ('is_purchasable', models.BooleanField(default=True, verbose_name='Achetable')),
                ('is_saleable', models.BooleanField(default=True, verbose_name='Vendable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
