# Generated by Django 5.0.4 on 2026-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Exonéré de TVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Laissez vide pour utiliser le taux par défaut de l'entreprise", max_digits=5, null=True, verbose_name='Taux TVA spécifique (%)'),
        ),
    ]
